---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.airflow.serviceAccount.name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.airflow.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["get", "create", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.airflow.serviceAccount.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.airflow.serviceAccount.name }}
roleRef:
  kind: Role
  name: {{ .Values.airflow.serviceAccount.name }}
  apiGroup: rbac.authorization.k8s.io