apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.airflow.service.name }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.airflow.name }} 
    name: {{ .Values.airflow.name }} 
  ports:
  - name: {{ .Values.airflow.service.name }}
    protocol: {{ .Values.airflow.service.protocol }}
    port: {{ .Values.airflow.service.port }}
    targetPort: {{ .Values.airflow.service.port }}

---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.postgresql.service.name }} 
spec:
  selector:
    app: {{ .Values.postgresql.service.name }} 
    name: {{ .Values.postgresql.service.name }} 
  ports:
  - name: {{ .Values.postgresql.service.name }} 
    protocol: {{ .Values.postgresql.service.protocol }} 
    port: {{ .Values.postgresql.service.port }} 
    targetPort: {{ .Values.postgresql.service.port }} 
