apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zk
  labels:
    app: zk
spec:
  replicas: 3
  selector:
    matchLabels:
      app: zk
  serviceName: zk-hs
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: zk
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "app"
                      operator: In
                      values:
                        - zk
                topologyKey: "kubernetes.io/hostname"
      containers:
      - name: zk
        image: zookeeper:3.6.2
        imagePullPolicy: Always
        env:
        - name: ALLOW_ANONYMOUS_LOGIN
          valueFrom:
            configMapKeyRef:
              name: nifi-config
              key: allow_anonymous_login
        - name: ZK_MONITOR_PORT
          valueFrom:
            configMapKeyRef:
              name: nifi-config
              key: zk_monitor_port
        volumeMounts:
        - name: config
          mountPath:  "/config"
          readOnly: true
        ports:
        - name: clustercoord
          containerPort: 2181
        - name: leader-election
          containerPort: 3888
        - name: server
          containerPort: 2888
      volumes:
      - name: config
        configMap:
          name: nifi-config
  volumeClaimTemplates:
  - metadata:
      name: zk-data
    spec:
      storageClassName: "zookeeper-sc"
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi