kind: Service
apiVersion: v1
metadata:
  name: jenkins-server
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: ui
      protocol: TCP
      port: 10000
      nodePort: 31000
      targetPort: 8080
  selector:
    app: jenkins-server
  type: NodePort