apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongodb.service.name }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.mongodb.name }} 
    name: {{ .Values.mongodb.name }} 
  ports:
  - name: {{ .Values.mongodb.service.name }}
    protocol: {{ .Values.mongodb.service.protocol }}
    port: {{ .Values.mongodb.service.port }}
    targetPort: {{ .Values.mongodb.service.port }}
