apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.init.name }}
  namespace: {{ .Release.Namespace }}
data:
  {{ .Values.configmap.init.fileName }}: |-
    var credentials = {
        "user": "{{ .Values.configmap.init.credentials.user }}",
        "password": "{{ .Values.configmap.init.credentials.password }}",
    }

    print('Creating databases....');
    db = db.getSiblingDB('db1');
    db.createUser({user: credentials.user, pwd: credentials.password, roles: [{role: "readWrite", db: "db1" }]});
    db.createCollection('customer');
    db.createCollection('sales');
    db.createCollection('products');

    db = db.getSiblingDB('db2');
    db.createUser({user: credentials.user, pwd: credentials.password, roles: [{role: "readWrite", db: "db2" }]});
    db.createCollection('products');
    db.createCollection('campaigns');
    db.createCollection('emails');
    db.createCollection('leads');

    db = db.getSiblingDB('db3');
    db.createUser({user: credentials.user, pwd: credentials.password, roles: [{role: "readWrite", db: "db3" }]});
    db.createCollection('user');
    db.createCollection('shares');

    print('Databases created.')

---
