apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.kafka.name }} 
spec:
  replicas: {{ .Values.image.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.kafka.name }} 
      name: {{ .Values.kafka.name }} 
  template:
    metadata:
      labels:
        app: {{ .Values.kafka.name }} 
        name: {{ .Values.kafka.name }} 
    spec:
      restartPolicy: {{ .Values.image.restartPolicy }}
      containers:
        - name: {{ .Values.kafka.name }} 
          image: "{{ .Values.kafka.repository }}:{{ .Values.kafka.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.kafka.service.port }} 
              protocol: {{ .Values.kafka.service.protocol }} 
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: {{ .Values.kafka.environment.zookeeper_connect }}
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: {{ .Values.kafka.environment.hostname }}
            - name: KAFKA_ADVERTISED_LISTENERS
              value: {{ .Values.kafka.environment.listeners }}
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: {{ .Values.kafka.environment.listener_security_protocol_map }}
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: {{ .Values.kafka.environment.inter_broker_listener_name }}
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: {{ .Values.kafka.environment.topic_replication_factor }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.zookeeper.name }} 
spec:
  replicas: {{ .Values.image.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.zookeeper.name }} 
      name: {{ .Values.zookeeper.name }} 
  template:
    metadata:
      labels:
        app: {{ .Values.zookeeper.name }} 
        name: {{ .Values.zookeeper.name }} 
    spec:
      restartPolicy: {{ .Values.image.restartPolicy }}
      containers:
        - name: {{ .Values.zookeeper.name }} 
          image: "{{ .Values.zookeeper.repository }}:{{ .Values.zookeeper.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.zookeeper.service.ports.client }} 
              protocol: {{ .Values.zookeeper.service.protocol }} 
            - containerPort: {{ .Values.zookeeper.service.ports.server_listen }} 
              protocol: {{ .Values.zookeeper.service.protocol }} 
            - containerPort: {{ .Values.zookeeper.service.ports.leader_elect }} 
              protocol: {{ .Values.zookeeper.service.protocol }} 
          env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: {{ .Values.zookeeper.environment.anon_login }}
            - name: ZOOKEEPER_CLIENT_PORT
              value: {{ .Values.zookeeper.environment.client_port }}
            - name: ZOOKEEPER_TICK_TIME
              value: {{ .Values.zookeeper.environment.tick_time }}