apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kafka.service.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.kafka.name }} 
    name: {{ .Values.kafka.name }} 
  ports:
  - name: {{ .Values.kafka.service.name }}
    protocol: {{ .Values.kafka.service.protocol }}
    port: {{ .Values.kafka.service.port }}
    targetPort: {{ .Values.kafka.service.port }}
  - name: {{ .Values.kafka.service.port2_name }}
    protocol: {{ .Values.kafka.service.protocol }}
    port: {{ .Values.kafka.service.port2 }}
    targetPort: {{ .Values.kafka.service.port2 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.zookeeper.service.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.zookeeper.name }} 
    name: {{ .Values.zookeeper.name }} 
  ports:
  - name: "{{ .Values.zookeeper.service.name }}-client"
    protocol: {{ .Values.zookeeper.service.protocol }}
    port: {{ .Values.zookeeper.service.ports.client }}
    targetPort: {{ .Values.zookeeper.service.ports.client }}
  - name: "{{ .Values.zookeeper.service.name }}-server"
    protocol: {{ .Values.zookeeper.service.protocol }}
    port: {{ .Values.zookeeper.service.ports.server_listen }}
    targetPort: {{ .Values.zookeeper.service.ports.server_listen }}
  - name: "{{ .Values.zookeeper.service.name }}-leader"
    protocol: {{ .Values.zookeeper.service.protocol }}
    port: {{ .Values.zookeeper.service.ports.leader_elect }}
    targetPort: {{ .Values.zookeeper.service.ports.leader_elect }}