version: 1
disable_existing_logging: False
formatters:
  format_debug:
    format: "%(asctime)s %(name)-50s %(levelname)-8s %(message)s"
  format_info:
    format: "%(asctime)-30s %(name)-50s %(levelname)-8s %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: format_info
    stream: ext://sys.stdout

  debug_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: format_debug
    filename: logs/debug.log
    maxBytes: 10485760
    backupCount: 2
    encoding: utf8

root:
  level: DEBUG
  handlers: [console, debug_file]